#!/bin/bash

echo "🚀 Iniciando todos los servicios de microservicios Kafka..."
echo ""

echo "📋 Instrucciones para ejecutar los servicios:"
echo ""
echo "1. Abre 3 terminales separadas"
echo "2. En cada terminal ejecuta uno de estos comandos:"
echo ""
echo "   Terminal 1 (User Service - Puerto 3001):"
echo "   npm run start:user-service"
echo ""
echo "   Terminal 2 (Create User Service - Puerto 3002):"
echo "   npm run start:create-user-service"
echo ""
echo "   Terminal 3 (Logging Service - Puerto 3003):"
echo "   npm run start:logging-service"
echo ""
echo "🌐 URLs de los servicios:"
echo "   - User Service: http://localhost:3001/users/:id"
echo "   - Create User Service: http://localhost:3002/users (POST)"
echo "   - Logging Service: http://localhost:3003/logs"
echo ""
echo "💡 Tip: Usa Ctrl+C en cada terminal para detener los servicios"
