stages:
  - install
  - test
  - security
  - build
  - deploy-staging
  - deploy-production

variables:
  PYTHON_VERSION: "3.11"
  DOCKER_REGISTRY: "registry.gitlab.com"
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE"

cache:
  key: 
    files:
      - requirements.txt
  paths:
    - .venv/
    - ~/.cache/pip/

.install_template: &install_template
  stage: install
  image: python:${PYTHON_VERSION}-slim
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  artifacts:
    paths:
      - .venv/
    expire_in: 1 hour

install:
  <<: *install_template

test:unit:
  stage: test
  image: python:${PYTHON_VERSION}-slim
  dependencies:
    - install
  before_script:
    - source .venv/bin/activate
    - pip install pytest pytest-cov flake8 black isort
  script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - black --check .
    - isort --check-only .
    - pytest --cov=app --cov-report=xml --cov-report=html
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage/
      - htmlcov/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:integration:
  stage: test
  image: python:${PYTHON_VERSION}-slim
  dependencies:
    - install
  services:
    - name: postgres:13-alpine
      alias: postgres
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_password
    DATABASE_URL: "postgresql://test_user:test_password@postgres:5432/test_db"
  before_script:
    - source .venv/bin/activate
    - pip install pytest-asyncio httpx
  script:
    - pytest tests/test_integration.py -v
  artifacts:
    paths:
      - test-results/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

security:safety:
  stage: security
  image: python:${PYTHON_VERSION}-slim
  dependencies:
    - install
  before_script:
    - source .venv/bin/activate
    - pip install safety
  script:
    - safety check --json --output safety-report.json
  artifacts:
    paths:
      - safety-report.json
    expire_in: 1 week
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

security:bandit:
  stage: security
  image: python:${PYTHON_VERSION}-slim
  dependencies:
    - install
  before_script:
    - source .venv/bin/activate
    - pip install bandit
  script:
    - bandit -r app/ -f json -o bandit-report.json
  artifacts:
    paths:
      - bandit-report.json
    expire_in: 1 week
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:latest
  dependencies:
    - test:unit
    - test:integration
    - security:safety
    - security:bandit
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:staging:
  stage: deploy-staging
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Deploying to staging environment..."
    - curl -X POST $STAGING_WEBHOOK_URL \
        -H "Content-Type: application/json" \
        -d "{\"image\": \"$DOCKER_IMAGE:$CI_COMMIT_SHA\"}"
    - echo "Waiting for deployment to complete..."
    - sleep 30
    - echo "Running smoke tests..."
    - curl -f $STAGING_HEALTH_CHECK_URL || exit 1
  environment:
    name: staging
    url: $STAGING_URL
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

deploy:production:
  stage: deploy-production
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Deploying to production environment..."
    - curl -X POST $PRODUCTION_WEBHOOK_URL \
        -H "Content-Type: application/json" \
        -d "{\"image\": \"$DOCKER_IMAGE:$CI_COMMIT_SHA\"}"
    - echo "Waiting for deployment to complete..."
    - sleep 60
    - echo "Running health checks..."
    - curl -f $PRODUCTION_HEALTH_CHECK_URL || exit 1
  environment:
    name: production
    url: $PRODUCTION_URL
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  when: manual

notify:slack:
  stage: .post
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        EMOJI="✅"
        COLOR="good"
      else
        EMOJI="❌"
        COLOR="danger"
      fi
      
      curl -X POST $SLACK_WEBHOOK_URL \
        -H "Content-Type: application/json" \
        -d "{\"attachments\": [{\"color\": \"$COLOR\",\"title\": \"$EMOJI Pipeline $CI_JOB_STATUS\",\"text\": \"Repository: $CI_PROJECT_NAME\nBranch: $CI_COMMIT_REF_NAME\nCommit: $CI_COMMIT_SHORT_SHA\",\"fields\": [{\"title\": \"Pipeline URL\",\"value\": \"$CI_PIPELINE_URL\",\"short\": true}]}]}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 